#!/bin/bash
# Download album cover for mpd
# needs mpc
# Usage : add this to your conkyrc
# ${execpi 5 /path/to/this/script}
# ${image /tmp/cover -s 75x75}
#
# By NanoSeb
# licence cc-by-sa


dossier=$HOME/.covers
cover=/tmp/cover
nocover=$HOME/Images/transparent.png

info=$(mpc -f "%artist% %album%" current | sed 's/\//+/g')

# MPD is not playing ...
if [ -z "$info" ] || [ "$info" = "error: Connection refused" ]
then
    rm "$cover"
    ln -s "$nocover" "$cover"
    exit 1
fi

file=$(sed 's/\ /+/g' <<< "$info")
search=$(sed 's/\ /+/g' <<< "$info")

if [ ! -e "$dossier/$file" ]
then


    page=$(wget -qO- "https://www.amazon.fr/s/ref=nb_sb_noss_1?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Dpopular&field-keywords=${search}")

    # curl can't connect to amazon.fr
    if [ "$?" = 6 ]
    then
        exit 2
    fi

    imageurl=$(grep "images-amazon.com\/images" <<<"$page"| grep jpg | grep "<img src=" -m 1 | awk -F "\"" '{print $2}')

    # does amazon.fr have this cover ?
    if [ -n "$imageurl" ]
    then
        curl -o "$dossier/$file" "$imageurl"
    else
        cp "$nocover" "$dossier/$file"
        rm "$cover"
        ln -s "$nocover" "$cover"
        exit 0
    fi

fi

rm "$cover"
if [ -e "$dossier/$file" ]
then
    ln -s "$dossier/$file" "$cover"
else
    ln -s "$nocover" "$cover"
fi

exit 0